/**:
  controller_manager:
    ros__parameters:
      update_rate: 20

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      base_controller:
        type: diff_drive_controller/DiffDriveController

      gpio_controller:
        type: gpio_controllers/GpioCommandController

  base_controller:
    ros__parameters:
      left_wheel_names: ["l_wheel_joint"]
      right_wheel_names: ["r_wheel_joint"]
      write_op_modes: ["motor_controller"]

      wheel_separation: 0.0961
      wheels_per_side: 1
      wheel_radius: 0.028

      wheel_separation_multiplier: 1.0
      left_wheel_radius_multiplier: 1.0
      right_wheel_radius_multiplier: 1.0

      odom_frame_id: odom
      base_frame_id: base_footprint
      pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
      twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

      position_feedback: true
      open_loop: false
      enable_odom_tf: true

      cmd_vel_timeout: 0.5
      publish_limited_velocity: false
      velocity_rolling_window_size: 10
      use_stamped_vel: false

      linear.x.has_velocity_limits: true
      linear.x.has_acceleration_limits: true
      linear.x.max_velocity: 0.5
      linear.x.min_velocity: -0.5
      linear.x.max_acceleration: 1.0

  gpio_controller:
    ros__parameters:
      gpios:
        - gpio
      command_interfaces:
        gpio:
          - interfaces:
            - enable_torque
            - set_led
      state_interfaces:
        gpio:
          - interfaces:
            - l_motor_enabled
            - l_motor_hw_error_status
            - l_motor_present_voltage
            - l_motor_present_temp
            - l_motor_led
            - r_motor_enabled
            - r_motor_hw_error_status
            - r_motor_present_voltage
            - r_motor_present_temp
            - r_motor_led